server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: user
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: none
    show-sql: false
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  kafka:
    bootstrap-servers:
      - localhost:9092
    consumer:
      group-id: 1
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring:
        json:
          trusted.packages: "com.example.eshop.entity"
